# Generated by Django 2.0.7 on 2018-09-03 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_addbuilder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_name', models.CharField(max_length=100)),
                ('add_address', models.CharField(max_length=100)),
                ('add_email', models.CharField(max_length=100)),
                ('add_phone', models.CharField(max_length=100)),
                ('add_exp', models.CharField(max_length=100)),
                ('add_quali', models.CharField(max_length=100)),
                ('add_pass', models.CharField(max_length=100)),
                ('add_image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='file')),
                ('add_approve', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_addwork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_name', models.CharField(max_length=100)),
                ('add_place', models.CharField(max_length=100)),
                ('add_prize', models.CharField(max_length=100)),
                ('add_sqrft', models.CharField(max_length=100)),
                ('add_typ', models.CharField(max_length=100)),
                ('add_image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='file')),
                ('add_nearby', models.CharField(max_length=100)),
                ('add_des', models.CharField(max_length=100)),
                ('add_bedrooms', models.CharField(max_length=100)),
                ('add_toilet', models.CharField(max_length=100)),
                ('add_floor', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conSub', models.CharField(max_length=100)),
                ('conName', models.CharField(max_length=100)),
                ('conemail', models.CharField(max_length=100)),
                ('conmsg', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('feedback', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_user', models.CharField(max_length=100)),
                ('log_pass', models.CharField(max_length=100)),
                ('log_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_requirment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField()),
                ('location', models.CharField(max_length=100)),
                ('floor', models.CharField(max_length=100)),
                ('sqrft', models.CharField(max_length=100)),
                ('bedrooms', models.CharField(max_length=100)),
                ('baths', models.CharField(max_length=100)),
                ('staircase', models.CharField(max_length=100)),
                ('kitchen', models.CharField(max_length=100)),
                ('plot', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='file')),
                ('plan', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='file')),
                ('des', models.CharField(max_length=100)),
                ('archid', models.IntegerField()),
                ('archplan', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='file')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_userreg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_name', models.CharField(max_length=100)),
                ('add_address', models.CharField(max_length=100)),
                ('add_email', models.CharField(max_length=100)),
                ('add_phone', models.CharField(max_length=100)),
                ('add_place', models.CharField(max_length=100)),
                ('add_approve', models.CharField(max_length=100)),
                ('add_pas', models.CharField(max_length=100)),
                ('add_lic', models.CharField(max_length=100)),
                ('add_image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='file')),
                ('add_type', models.CharField(max_length=100)),
            ],
        ),
    ]
