# Generated by Django 2.1.1 on 2018-09-03 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_userreg',
        ),
    ]
