# Generated by Django 2.1.1 on 2018-09-03 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_tbl_userreg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_userreg',
            name='add_desc',
            field=models.CharField(max_length=1000),
        ),
    ]
