# Generated by Django 2.1.1 on 2018-09-03 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0004_auto_20180903_0544'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_userreg',
        ),
    ]
