# Generated by Django 2.1.1 on 2018-09-03 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0006_tbl_userreg'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_addwork',
        ),
    ]
