# Generated by Django 2.1.1 on 2018-09-04 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0009_tbl_addprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_addprofile',
        ),
    ]
