# Generated by Django 2.1.1 on 2018-09-05 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0011_tbl_addprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='imagesupload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imag', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='file')),
            ],
        ),
    ]
