# Generated by Django 2.1.1 on 2018-09-06 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0012_imagesupload'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_addbuilder',
        ),
    ]
