# Generated by Django 2.1.1 on 2018-09-06 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0015_delete_tbl_addbuilder'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_builder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_name', models.CharField(max_length=100)),
                ('add_address', models.CharField(max_length=100)),
                ('add_email', models.CharField(max_length=100)),
                ('add_phone', models.CharField(max_length=100)),
                ('add_exp', models.CharField(max_length=100)),
                ('add_quali', models.CharField(max_length=100)),
                ('add_pass', models.CharField(max_length=100)),
                ('add_image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='file')),
                ('add_approve', models.CharField(max_length=100)),
            ],
        ),
    ]
