# Generated by Django 2.1.1 on 2018-09-06 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0017_auto_20180906_0851'),
    ]

    operations = [
        migrations.DeleteModel(
            name='imagesupload',
        ),
    ]
