# Generated by Django 2.1.1 on 2018-09-06 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0019_imagesupload'),
    ]

    operations = [
        migrations.DeleteModel(
            name='imagesupload',
        ),
    ]
