# Generated by Django 2.1.1 on 2018-09-13 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0028_tbl_garden'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_garden',
        ),
    ]
