# Generated by Django 2.1.1 on 2018-09-14 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0030_tbl_garden'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_requirment',
        ),
    ]
