# Generated by Django 2.1.1 on 2018-09-14 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0031_delete_tbl_requirment'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_requirment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField()),
                ('location', models.CharField(max_length=100)),
                ('floor', models.CharField(max_length=100)),
                ('sqrft', models.CharField(max_length=100)),
                ('bedrooms', models.CharField(max_length=100)),
                ('baths', models.CharField(max_length=100)),
                ('staircase', models.CharField(max_length=100)),
                ('kitchen', models.CharField(max_length=100)),
                ('plot', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='file')),
                ('plan', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='file')),
                ('des', models.CharField(max_length=100)),
                ('archid', models.IntegerField()),
                ('archplan', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='file')),
                ('archcost', models.CharField(max_length=100)),
            ],
        ),
    ]
