# Generated by Django 2.1.1 on 2018-09-14 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0032_tbl_requirment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_requirment',
        ),
    ]
