# Generated by Django 2.1.1 on 2018-09-20 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0039_tbl_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_sugg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField()),
                ('workid', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('sugg', models.CharField(max_length=100)),
                ('rply', models.CharField(max_length=100)),
            ],
        ),
    ]
