# Generated by Django 2.1.1 on 2018-09-22 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0041_tbl_wrkassgn'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_wrkassgn',
        ),
    ]
