# Generated by Django 2.1.1 on 2018-09-22 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0045_delete_tbl_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField()),
                ('workid', models.IntegerField()),
                ('price', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('payment', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
            ],
        ),
    ]
