# Generated by Django 2.1.1 on 2018-10-02 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0047_delete_tbatm'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbatm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Atmno', models.CharField(max_length=14)),
                ('amt', models.CharField(max_length=15)),
                ('expm', models.CharField(max_length=2)),
                ('expy', models.CharField(max_length=100)),
                ('cvv', models.CharField(max_length=3)),
            ],
        ),
    ]
