# Generated by Django 2.1.1 on 2018-10-02 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0048_tbatm'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbatm',
        ),
    ]
